### ISSUE TITLE
Re-add sticky people-dropdown & CV/Skills-tab

### ISSUE THREAD

**Issue by ManuelMoeri** [puzzle/skills#701]
The scrolling behaviour should have been fixed by #692 (if not pls don't do this issue yet.) While the scrolling is perfect, the header with the people-dropdown seems to move strangely when scrolling down. The CV/Skills-tab does not even move at all. Make sure to fix this in the profile view.

It's kinda hard to describe or take pictures but I've tried. Maybe just go check it out for yourself and look at the difference.

*Before scrolling*
![Image](https://github.com/puzzle/skills/assets/109959820/b036b2ee-d62f-493d-b97d-ddabe3ea0b35)

*After scrolling*
![Image](https://github.com/puzzle/skills/assets/109959820/3b10ec94-5989-448a-bff4-6b5ab828c37d)

*In the old application*
![Image](https://github.com/puzzle/skills/assets/109959820/279d9633-eb82-4de9-b1fa-ed7028dab231)

### ToDo:
- [ ] Fix behaviour of people-dropdown
- [ ] Fix behaviour of CV/Skills-tab
- [ ] Compare with old application for other differences in the "header"
- [ ] Maybe update tests
