### ISSUE TITLE
Look at API | PuzzleTime Sync #1

### ISSUE THREAD

**Issue by RandomTannenbaum** [puzzle/skills#732]
**Introduction**
We need to know which attributes from the PuzzleTime person model we can use in the Skills model. For this we need to take a look at the API of the PuzzleTime. Since the PuzzleTime does not have a API documentation we will have to figure it out ourself. Once we know how the API works we can create this missing documentation in the PuzzleTime.

**ToDo**
- [x] Talk to @Kagemaru because he wrote the API :grin: 
- [x] Take a look at the PuzzleTime API and find out how it works
- [x] Find out and document which fields we get from PuzzleTime and which fields we can use in PuzzleSkills
- [x] Make sure to link the document with all the attributes we'll use directly in the ticket or as a comment
- [x] Create a PR for updating the PuzzleTime documentation with a short API docu

**Comment by ManuelMoeri** [comment]
**19.07.2024**
Everything I found out today is writen in this codi: https://codimd.puzzle.ch/COP3-usSQc2STNoul0Uvvg#
I also did a little testing with postman to see which endpoints I could reach which kinda worked.

**Comment by RandomTannenbaum** [comment]
**Stand 21.06.2024**
Ich habe mir die API angeschaut und auf [@ManuelMoeri s codi](https://codimd.puzzle.ch/COP3-usSQc2STNoul0Uvvg#) aufgebaut.

In diesem neuen codi sind nun alle mappbaren Felder sowie die API inkl. Authentication beschrieben:
https://codimd.puzzle.ch/0v-AaUXWRfmDWYS5N3jKPA?both

**Comment by ManuelMoeri** [comment]
Has been done a long time ago.
