### ISSUE TITLE
Make Skills attr readonly for ptime attrs | PuzzleTime Sync #4

### ISSUE THREAD

**Issue by kcinay055679** [puzzle/skills#733]
**Introduction**
After mapping every attribute we need from the PuzzleTime we will need to display them and make them read-only. This is necessary since PuzzleTime will be our source of truth. This results in only beeing able to edit these attributes in the PuzzleTime.

Additionally we want to have a visual feature for the user. This feature should show the user why he can't edit these fields. We also want to have a "manual sync" button to trigger the job manually and fetch the data.

**ToDo**
- [x] Look at all the attributes we get from PuzzleTime (should be documented in #732)
- [x] Make all these attributes read-only so PuzzleTime is and stays the source of truth
- [x] Design some kind of visual feature to mark the non-editable attributes and show it to robin to gain his approval
- [x] Implement this viusal feature preferably with a hoverable text that says where it's managed or why it's not editable
- [x] Last but not least, make sure to implement the "manual sync" button
- [x] Tests

**Comment by ManuelMoeri** [comment]
> ## Stand 18.03.2025
> 
> I have implemented that the attributes that get loaded out of the puzzle time are disabled if you want to edit a profile if the sync is off the functionality stayed the same. I also added tooltips that tell the person why they can't edit that attribute.
> #### Still To-Do:
> 
>     * [ ]  Tests[ ]  ~The Manuel sync button~

The manual sync button is not needed anymore since we have flexible updating now. 😄
