### ISSUE TITLE
Remove editing of Skills in skillset for all people

### ISSUE THREAD

**Issue by ManuelMoeri** [puzzle/skills#750]
**Describe the bug**
Currently when visiting [skills](https://skills.puzzle.ch/) and heading to the 'Skillset' tab you'll see a edit icon at the end of every skill. This should only be the case if you have the admin role, currently it's available to everyone. Luckily it does not work, it simply says 'Content missing' when clicking on it.

**How to fix it**
You will simply have to check the roles implementation and see why this is not working correctly. Also make sure to test it out with a admin role. Because if they can't edit it either, this needs to be fixed too.

**ToDo**
- [ ] Editing only possible for those with admin rights
- [ ] Make sure editing with the correct role is actually possible
- [ ] TESTS -> Definitely add tests for this scenario
- Ⓜ️Ⓜ️
