### ISSUE TITLE
Make Buttons and Dropdowns Turbo 8 friendly

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#755]
Depends on this being completed: https://github.com/puzzle/skills/issues/752

Turbo 8 adds Link-Preloading. This works perfecty fine for normal links but not for e.g. The People dropdown because those probably aren't normal links. Some dropdown libraries have a option to display the elements as links. Maybe ours has that.

TODO:
- Check which buttons, dropdowns or actual links that don't work with Link-Preloading yet
- Try to fix as many of those wherever possible
- Make sure performance doesn't become an issue (e.g. In the People Dropdown scrolling over "all" the people when looking through the list will then send a request each which might be a bit too much)

**Comment by RandomTannenbaum** [comment]
**ToDo**
- [ ] Check links in application and document which do not work yet with link preloading -> especially check slim select dropdowns
- [ ] Fix those that are possible
- [ ] Smoke Test
- [ ] Review

**Comment by RandomTannenbaum** [comment]
**ToDo**
- [ ] Find good timeout for link prefetching in people dropdown
- [ ] Check possibilities for prefetching on-hover
- [ ] Check performance impact on server
