### ISSUE TITLE
IT-Ninjas Oktober 2024 vorbereiten

### ISSUE THREAD

**Issue by ManuelMoeri** [puzzle/skills#767]
### TODO
- [ ] Alle beteiligten wissen was sie zu tun haben
- [ ] Alle Tools & Repos wurden kurz getestet und sind ready
- [ ] Nur für Roboter-Posten: Der Postne ist aufgestellt und bereit für die Schnupperlis
- [ ] Sämtliche Links zu Posten beschreibungen & ähnliches wurden an einem Ort gesammelt (z.B. dieses Ticket)

**Comment by Robin481** [comment]
Please open this issue in https://github.com/puzzle-bbt/bbt
