### ISSUE TITLE
Concept: Unifying of Duplicate Skills

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#768]
Sometimes skills will be added that are either the same or very similar.
There should be an option to merge skills and the members that have filled out this skill should be moved over as well.
There should be some sort of admin view where the two correlating skills can be selected and merged. 
It should allow the user to chose which skill to keep and which skill to merge into it. 

TODO:
- Create a mockup for an admin view where this would be possible
- Think through the possible pitfalls

**Comment by hupf** [comment]
Maybe also rework the UX of the addition of a skill?

→ Make it very easy to use an existing skill, make it hard to create a new one.

**Comment by nevio18324** [comment]
### Todo's ###
- [ ]     Create a mockup for an admin view where this would be possible
- [ ]     Think through the possible pitfalls
- [ ]     Above everything data loss should not be possible. Think about using transactions or using some kind of logging that would allow to reverse to the old state.
- [ ]     Create Tickets

**Comment by nevio18324** [comment]
### Stand 3.3 ###
Ich habe jeweils ein beispiel und eine Skizze in [Figma](https://www.figma.com/design/aUEWL5uHBY3CBaazAKl03Y/Merge-Skills?node-id=0-1&p=f&t=o7nandHJvK53iCRc-0) erstellt wie das ganze aussehen könnte

**Comment by nevio18324** [comment]
### 6.3 ###
Ich habe nun zwei Tickets erstellt die dieses Problem lösen sollten einmal eins fürs [backend](https://github.com/puzzle/skills/issues/823) und eins für die [View](https://github.com/puzzle/skills/issues/821)
